[package]
name = "jh-hello-htmx"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
shuttle-rocket = "0.14.0"
shuttle-runtime = "0.14.0"
tokio = "1.26.0"

rocket = "0.5.0-rc.2"
shuttle-static-folder = "0.14.0"
rocket_dyn_templates = { version = "0.1.0-rc.2", features = ["handlebars"] }